plugins {
    id 'com.android.application'
}

android {
    namespace 'com.remote.control'
    compileSdk 33

    defaultConfig {
        applicationId "com.remote.control"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'io.socket:socket.io-client:2.0.1'
}
